server:
  port: 7270
shiro:
  plugin-list:
    - com.catand.skyblockhelper.plugins.LogPlugin
    - com.catand.skyblockhelper.plugins.HelpPlugin
    - com.catand.skyblockhelper.plugins.NetworthPlugin
    - com.catand.skyblockhelper.plugins.SkillPlugin
    - com.catand.skyblockhelper.plugins.MissingPlugin
    - com.catand.skyblockhelper.plugins.DungeonPlugin
    - com.catand.skyblockhelper.plugins.TrophyFishPlugin
    - com.catand.skyblockhelper.plugins.SlayerPlugin
    - com.catand.skyblockhelper.plugins.HOTMPlugin
    - com.catand.skyblockhelper.plugins.ProfilePlugin
    - com.catand.skyblockhelper.plugins.BingoPlugin
    - com.catand.skyblockhelper.plugins.NoSuchCommandPlugin
  interceptor: